### ISSUE TITLE
All gradients equal zero

### ISSUE THREAD

**Issue by fedebenelli** [zoziha/Auto-Diff#2]
Hello! First of all thanks for developing this! I find automatic differentiation very exiting and an incredible tool for my work

 I'm trying to use this library for a project, but for some reason I can't get any derivatives values. Not even the examples are running for me:

```
demo1: y = (a + b*b)*exp(c)
 y     =    3.00000000    
 dy/da =    0.00000000    
 dy/db =    0.00000000    
 dy/dc =    0.00000000    
 
 demo2: y = (a + b)*(b + 1.0)
 y     =    6.00000000    
 dy/da =    0.00000000    
 dy/db =    0.00000000  
 ```
This happens on all examples 

 Any idea about what could this be?

I also tried the recommended fazang library but couldn't even link it to a simple main program :/

**Comment by zoziha** [comment]
I am very sorry, this repository is just **a toy project**, it does not have a good data structure, it can only generate right results under `gfortran`, and uses features not standardized by the Fortran standard.

As for fazang, unfortunately it seems that the author stopped developing it about a year ago and introduced Sundials, out of curiosity [I moved fazang and removed the ODE support and now it is compilable](https://github.com/zoziha/fazang).

It's worth noting that Fortran lacks enough new open source developers and fazang is in early alpha, so if you need to use fazang it may mean you need extra work for it.

**Comment by fedebenelli** [comment]
Thank you for your response and the fixed fazang fork!!
I'm new into using meson, I've tried compiling with:

```bash
mkdir build
cd build; meson setup; meson compile
```

Which gives me both a `libfazang.so` and a `libfazang.a`

I've tried compiling a simple `main.f90` just copying the lines on the readme file. And compiling with either

```bash
gfortran -o main main.f90 -L. -I. -lfazang
```

```bash
gfortran -o main main.f90 libfazang.a -L. -I.
```

In either case I get 
```
main.f90:2:7:

    2 |   use fazang ! load Fazang library
      |       1
Fatal Error: Cannot open module file ‘fazang.mod’ for reading at (1): No such file or directory
compilation terminated.
```

Sorry this isn't your library, but just in case you could give a little insight in what I'm doing wrong.

Thanks!

**Comment by zoziha** [comment]
It looks like you didn't move the `*.mod` files, which are Fortran binary header files used to access interfaces to the link library at compile time.

**Comment by fedebenelli** [comment]
Thanks! That was it, thought that the `*.mod` files were also included in the library
